pipeline {
    agent any

    tools {
        maven 'Maven-3.9'   // TEM que bater com o nome no Jenkins
    }

    stages {
        stage('Test') {
            steps {
                bat 'mvn -B test'
            }
        }
    }
}